### ISSUE TITLE
something wrong with readme

### ISSUE THREAD

**Issue by oycq** [AI4Finance-LLC/ElegantRL#12]
python3 AgentRun.py
# You can see run__demo(gpu_id=0, cwd='AC_BasicAC') in AgentRun.py.

python3: can't open file 'AgentRun.py': [Errno 2] No such file or directory

chengdu-pijialonggui-CV

**Comment by oycq** [comment]
where is AgentRun.py?

**Comment by XiaoYangLiu-FinRL** [comment]
We rename it to main.py.
