### ISSUE TITLE
Main.py can not work with DEMO 2

### ISSUE THREAD

**Issue by oycq** [AI4Finance-LLC/ElegantRL#13]
My python version is 3.6.9

and I just uncomment DEMO2 and comment DEMO3

Then I got the error message below:

/usr/local/lib/python3.6/dist-packages/gym/logger.py:30: UserWarning: WARN: Box bound precision lowered by casting to float32
  warnings.warn(colorize('%s: %s'%('WARN', msg % args), 'yellow'))
| env_name: LunarLanderContinuous-v2, action space: Continuous
| state_dim: 8, action_dim: 2, action_max: 1.0, target_reward: 200
| GPU id: n, cwd: ./AgentModSAC/LunarLanderContinuous-v2_n
| Remove history
Traceback (most recent call last):
  File "Main.py", line 312, in <module>
    main()
  File "Main.py", line 77, in main
    train_and_evaluate(args)
  File "Main.py", line 134, in train_and_evaluate
    agent = rl_agent(net_dim, state_dim, action_dim)
  File "/home/oycq/gym/ElegantRL/Agent.py", line 468, in __init__
    AgentSAC.__init__(net_dim, state_dim, action_dim, learning_rate)
  File "/home/oycq/gym/ElegantRL/Agent.py", line 406, in __init__
    super().__init__()
TypeError: super(type, obj): obj must be an instance or subtype of type

**Comment by Yonv1943** [comment]
Ok. I had fix it.
