### ISSUE TITLE
Can't run in colab

### ISSUE THREAD

**Issue by udp-justin-lee** [AI4Finance-LLC/ElegantRL#21]
I meet the error below

![image](https://user-images.githubusercontent.com/8622121/111711495-2fe26880-888f-11eb-90f8-a31c9f6b083d.png)

**Comment by Yonv1943** [comment]
We are trying to solve this problem. 
We will reply you after the problem is resolved, thank you.

**Comment by supersglzc** [comment]
> I meet the error below
> 
> ![image](https://user-images.githubusercontent.com/8622121/111711495-2fe26880-888f-11eb-90f8-a31c9f6b083d.png)

Fixed.
