### ISSUE TITLE
env error

### ISSUE THREAD

**Issue by cyberslam** [AI4Finance-LLC/ElegantRL#31]
Thank you for such a wonderful program.
I was trying to run "eRL_demo_StockTrading.ipynb" under Colab
via "cut and paste".

At the very end and after training, I ran into this error:

Last code block:

args = Arguments(if_on_policy=True)
args.agent = AgentPPO()
args.env = StockTradingEnv(cwd='./', if_eval=True)
args.if_remove = False
args.cwd = './AgentPPO/StockTradingEnv-v1_0'
args.init_before_training()

env.draw_cumulative_return(args, torch)

Error Message under Colab:

GPU id: 0, cwd: ./AgentPPO/StockTradingEnv-v1_0
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-6-e8a0261f66cc> in <module>()
      6 args.init_before_training()
      7 
----> 8 env.draw_cumulative_return(args, torch)

NameError: name 'env' is not defined

How could I solve this??   Pls help!

**Comment by yoshishima** [comment]
Try changing it to: **_args_**.env.draw_cumulative_return(args, torch)

**Comment by cyberslam** [comment]
AHHH, it worked.  Thank you very much for the correction.
I could reproduce the graph now - I will close this issue.

**Comment by cyberslam** [comment]
The correction worked.  Many thank.  :)

**Comment by yoshishima** [comment]
No problem. I had the same issue.
