### ISSUE TITLE
Offline data support.

### ISSUE THREAD

**Issue by veioxve3r1d23seb2g6b** [AI4Finance-LLC/ElegantRL#40]
Would you happen to have offline example for stock? Some tickers are not available on yahoo finance.

**Comment by XiaoYangLiu-FinRL** [comment]
Please check out the other repo for many data sets / APIs:  https://github.com/AI4Finance-LLC/NeoFinRL

**Comment by veioxve3r1d23seb2g6b** [comment]
Thanks!
